name: full_example
description: An example project that demonstrates all Widgetbook features.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.17+3
  widgetbook: ^3.3.0
  widgetbook_annotation: ^3.0.0
  xml: ^6.3.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.4
  widgetbook_generator: ^3.2.0

flutter:
  uses-material-design: true
  
assets:
  -assets/README.md
  -assets/data.xml