name: full_example
description: An example project that demonstrates all Widgetbook features.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.3.0
  widgetbook_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.4
  widgetbook_generator: ^3.2.0

flutter:
  uses-material-design: true
